### ISSUE TITLE
Performance of DEPS with GT plan as starting point? 

### ISSUE THREAD

**Issue by simon-lund** [CraftJarvis/MC-Planner#10]
Hello,

do you have data about the performance of DEPS when it's initially given the ground truth plan? 

I would be interested in it's maximum achievable performance. Since the tasks are well known and ground truth exist, why not use them as a blueprint / starting point? 

Best 
Simon

**Comment by zhwang4ai** [comment]
Thank you for your inquiry. We have updated arXiv and reported the success rate of DEPS completing various tasks in textworld under the given oracle controller in Table 3. 
For another issue, although these tasks can be completed using a manually designed plan+controller, in open-world Minecraft, a fixed groundtruth plan cannot guarantee the completion of the task. For example, different types of logs may be required in different biomes; during the process of finding diamonds, an iron pickaxe may get worn out. DEPS can reliably complete tasks in various environments based on the agent's situation through close-loop re-planning.

**Comment by simon-lund** [comment]
Thank you :+1:
