### ISSUE TITLE
Error on execution of main.py

### ISSUE THREAD

**Issue by speedhawk** [CraftJarvis/MC-Planner#11]
Hi! This is really a great work and many thanks for sharing it! However, I found the main.py cannot be executed by the command you supplied after reading your paper and tried to reimplement it on Colab:
`!python main.py model.load_ckpt_path=<path/to/ckpt>`

in which '!' should be added in front of 'python'.
And this is the error report:
```
/bin/bash: -c: line 0: syntax error near unexpected token `newline'
/bin/bash: -c: line 0: `python main.py model.load_ckpt_path=<path/to/ckpt>'

```
Is this meaning I should modify the path in 'simple.yaml' file of model folder? Could you please help to check and fix it? Many thanks!

**Comment by zhwang4ai** [comment]
It seems that you need to manually download the checkpoint file from [url](https://pkueducn-my.sharepoint.com/:f:/g/personal/zhwang_pkueducn_onmicrosoft_com/Ev7WGWHL5PpCjMKil0dYrOUB8nw0Yqd8KUyfB47uxgoJow?e=xTgtPY). And replace `<path/to/ckpt>` with the downloaded checkpoint file location.
