### ISSUE TITLE
Weight File Download Issue

### ISSUE THREAD

**Issue by 3DAlgoLab** [CraftJarvis/MC-Planner#15]
Weight files([ReadMe](https://github.com/CraftJarvis/MC-Planner/blob/main/README.md)) from this repository is all I need when I evaluate the model?
When I tried to download the weight file, in the [MC-Controller](https://github.com/CraftJarvis/MC-Controller), it was linked to the Baidu site. I could not join the site although I tried to login as a foreigner.

**Comment by zhwang4ai** [comment]
The weight file can be found in this [URL](https://pkueducn-my.sharepoint.com/:f:/g/personal/zhwang_pkueducn_onmicrosoft_com/Ev7WGWHL5PpCjMKil0dYrOUB8nw0Yqd8KUyfB47uxgoJow?e=xTgtPY).
