### ISSUE TITLE
论文中VPT获取钻石的成功率应该是20%，而不是2.5%

### ISSUE THREAD

**Issue by Yun-Peng-Wang** [CraftJarvis/MC-Planner#8]
论文中VPT获取钻石的成功率应该是20%，而不是2.5%，2.5%成功率的是钻石镐吧

**Comment by zhufq00** [comment]
It is indeed so.

VPT Paper: https://arxiv.org/pdf/2206.11795.pdf

The three-phase training (pretraining, BC fine-tuning, and then RL fine-tuning) succeeds in learning extremely difficult tasks: it achieves over 80% reliability on iron pickaxes, almost **20% reliability on collecting diamonds**, and
2.5% reliability on obtaining a diamond pickaxe (Fig. 7d).

**Comment by YitaoLiang** [comment]
Would correct it. The issue would remain opened until our new draft is online.Best,YitaoOn Jul 20, 2023, at 17:24, zhufq ***@***.***> wrote:﻿
It is indeed so.
VPT Paper: https://arxiv.org/pdf/2206.11795.pdf
The three-phase training (pretraining, BC fine-tuning, and then RL fine-tuning) succeeds in learning extremely difficult tasks: it achieves over 80% reliability on iron pickaxes, almost 20% reliability on collecting diamonds, and
2.5% reliability on obtaining a diamond pickaxe (Fig. 7d).

**Comment by zhwang4ai** [comment]
Thanks for your comments. We have updated the article at https://arxiv.org/pdf/2302.01560.pdf
